/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_MainActivity */

#ifndef _Included_com_darly_ndkclient_MainActivity
#define _Included_com_darly_ndkclient_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_MainActivity
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_darly_ndkclient_MainActivity_getNDKStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
